import {ArrowRight,CheckCircle2,ClipboardCheck,FileSearch,Globe2,MessageCircle,Route,ShieldCheck,Target} from "lucide-react";
const services=[{title:"ANVISA",text:"AFE, registros, notificações, Boas Práticas de Fabricação e Hosting Service."},{title:"MAPA",text:"Licenças de estabelecimento, registro de produtos, boas práticas e renovações."},{title:"Viabilidade Regulatória",text:"Enquadramento, requisitos, avaliação de riscos e estratégia de entrada no Brasil."}];
const steps=[[FileSearch,"Entendimento"],[Route,"Estratégia"],[ClipboardCheck,"Execução"],[CheckCircle2,"Acompanhamento"]] as const;
export default function Home(){return <><header><div className="container nav"><a className="logo" href="#inicio">LEGARE <small>Serviços e Soluções Regulatórias</small></a><nav><a href="#sobre">Sobre</a><a href="#servicos">Serviços</a><a href="#processo">Como trabalhamos</a><a className="btn sm" href="#contato">Orçamento</a></nav></div></header><main>
<section className="hero" id="inicio"><div className="container hero-grid"><div><h1>Regulação sem burocracia.<br/><span>Resultados com segurança.</span></h1><p>Soluções regulatórias completas para empresas que querem entrar ou expandir no Brasil com conformidade junto à ANVISA e ao MAPA.</p><div className="actions"><a className="btn" href="#contato"><MessageCircle/>Fale com um especialista</a><a href="#servicos">Conheça os serviços <ArrowRight/></a></div></div><div className="visual"><div>ANVISA</div><Globe2/><div>MAPA</div></div></div></section>
<section className="section" id="servicos"><div className="container"><Title label="Nossos serviços" text="Expertise regulatória para abrir caminhos."/><div className="services">{services.map((s,i)=><article key={s.title}><b>0{i+1}</b><h3>{s.title}</h3><p>{s.text}</p><a href="#contato">Fale com um especialista <ArrowRight/></a></article>)}</div></div></section>
<section className="stats"><div className="container"><Stat icon={<Target/>} big="13+ anos" text="de experiência"/><Stat icon={<ShieldCheck/>} big="95%" text="de aprovação em 2025"/><Stat icon={<Globe2/>} big="40+ países" text="atendidos"/></div></section>
<section className="section" id="processo"><div className="container"><Title label="Como trabalhamos" text="Um processo claro para resultados consistentes."/><div className="steps">{steps.map(([Icon,t],i)=><article key={t}><i>{i+1}</i><Icon/><h3>{t}</h3><p>Condução técnica, personalizada e comunicação clara em todas as etapas.</p></article>)}</div></div></section>
<section className="section about" id="sobre"><div className="container about-grid"><div><p className="label">Sobre a LEGARE</p><h2>Parceria que transforma regulação em crescimento.</h2><p>A LEGARE é especializada em assessoria e consultoria regulatória junto à ANVISA e ao MAPA. Cada projeto recebe uma estratégia personalizada e acompanhamento direto de especialistas.</p></div><div className="panel">LEGARE<small>Regulatory Affairs<br/>Global Business</small></div></div></section>
<section className="contact" id="contato"><div className="container"><div><p>Vamos conversar sobre o seu projeto?</p><h2>Transforme a complexidade regulatória em um caminho claro.</h2></div><div><a className="btn light" href="https://wa.me/5516991733137"><MessageCircle/>WhatsApp</a><a href="mailto:contato@LEGARE.com.br">contato@LEGARE.com.br</a><a href="tel:+5516991733137">(16) 99173-3137</a></div></div></section></main><footer><div className="container">LEGARE — Serviços e Soluções Regulatórias <span>© 2026</span></div></footer></>}
function Title({label,text}:{label:string;text:string}){return <div className="title"><p>{label}</p><h2>{text}</h2></div>}function Stat({icon,big,text}:{icon:React.ReactNode;big:string;text:string}){return <div>{icon}<strong>{big}</strong><span>{text}</span></div>}
